### ISSUE TITLE
Represent vectors as binaries

### ISSUE THREAD

**Issue by seanmor5** [pgvector/pgvector-elixir#6]
Hey @ankane thank you for this! I just set something up with pgvector and it was seamless!

I have one question:

From the Elixir side can we represent vectors as binaries? It seems the underlying vector type in Postgres is already a binary and so the list conversion is an extra step. Additionally, when using [Nx](https://github.com/elixir-nx/nx) we can avoid the additional overhead of converting a tensor to a list. Tensors internally are represented as binaries.

There are a few drawbacks:

1. Migration for users who already use the list representation
2. Consumers of external embedding APIs. Most APIs will return the vector as a list because of the JSON response

If you're open to this, I'm willing to contribute the change

**Comment by ankane** [comment]
Hi @seanmor5, curious to see what this would look like (if it wouldn't take too long to put together).

Also, just added conversion *from* Nx tensors in 91e048f2af6787324afbcfaefafcaa9791bb2e47 for Ecto to make things more user-friendly.

**Comment by josevalim** [comment]
Oh, nice discussion!

My suggestion would be for the extension to work only with binaries. That's because binaries are the cheapest representation of vectors in Elixir (they are contiguously allocated compared to lists which are linked lists) and most times we will be able to do zero copy operations with them (since they are ref counted). In a nutshell, encoding would be roughly this:

    [<<byte_size(binary)+2::int32, div(byte_size(binary), 4)::uint16, 0::uint16>> | data]

And decoding is:

    <<_len::int32, dim::uint16, 0::uint16, bin::binary-size(dim)-unit(32)>> ->
      bin

At this point, zero copying has happened on both writes and reads (actually, it will depend on the value of decode_binary, and it defaults to copy to avoid references to large messages, but it is customizable for those with alrge vectors). And if later we plug them into a tensor, there is also zero copying!

This way, you shouldn't need an Ecto.Type in this extension either, as folks can use binary directly in Ecto today. But if you want better integration with Nx, you could have an EctoNx type (perhaps a parameterized type), where you specify the tensor type like this:

    field :foo, EctoNx, type: :f32

And that will:

  1. Load and cast the binary into a tensor with the given type
  2. Dump to a binary

But I think the Nx tensor bits could be build as a separate library, since it is not pgvector specific, in case you don't want to worry!

PS: if you default to binaries, you may have a concern with backwards compatibility. One option is to use init to customize how you want to encode/decode, but perhaps it may be more sensible to ship v0.2 with the new defaults. I would also be very glad to submit PRs here. <3

**Comment by ankane** [comment]
Thanks @josevalim. As a first step of prototyping this, I ran into an issue with endianness when trying to update [this method](https://github.com/pgvector/pgvector-elixir/blob/adb9a3d16613420800a95f66da2ddfb3cdbc0e0c/lib/pgvector/extensions/vector.ex#L33-L35).

```elixir
def encode_vector(t) when is_struct(t, Nx.Tensor) do
  dim = Nx.size(t)
  bin = Nx.to_binary(Nx.as_type(t, :f32))
  [<<dim::uint16>>, <<0::uint16>> | bin]
end
```

Is there a way to serialize and deserialize tensors in big-endian byte order?

**Comment by josevalim** [comment]
Tensors are always in native order (you can find it as `System.endianness`). So you could do this:

```elixir
defp f32_to_big(binary) do
  if System.endianness() == :big do
    binary
  else
    for <<n::f32-little <- binary>>, do: <<n::f32-big>>
  end
end
```

If `f32` is not available (those shortcuts are Postgrex conveniences), you can write it as `float-32`.

**Comment by ankane** [comment]
Thanks @josevalim, working great!

To all: Added one possible approach to the [struct branch](https://github.com/pgvector/pgvector-elixir/compare/struct). It returns a `Vector` struct that stores the binary representation internally, and there are `to_list` and `to_tensor` methods to convert to either type. Let me know if you have any thoughts or feedback.

**Comment by josevalim** [comment]
@ankane looks great! Some nitpicks:

1. In theory, you could define `Pgvector` itself as a struct and skip the additional module

2. Nitpick on my own code: `f32_to_big` should probably have been called `f32_native_to_big`

3. Nitpick on my own code: we should do `for <<n::float-32-little <- bin>>, into: "", do: <<n::float-32-big>>`. This makes the output a binary and avoids allocating a linked list. The compiler is also smart enough to know that you are converting to a binary of the same size and do a single and efficient preallocation

4. For inspect, the convention in Elixir would be `Pgvector.new([1, 2, 3, 4])`, so inspection is executable (at least whenever possible). So I wonder if we should instead rename `vector` to `new` and make it also accept binaries?

---

So I am now thinking about the benefits of using a custom struct vs binary. A custom struct is easier to identity and allow us to provide further functionality in the future, compared to only using binaries. But it requires an Ecto extension (it should be super simple extension though). The binary is lower level and does not require an Ecto extension. Probably better to go with the struct. :)

**Comment by ankane** [comment]
Great, all that makes sense to me. Just pushed an update to the [struct2 branch](https://github.com/pgvector/pgvector-elixir/compare/struct2) and it feels cleaner. Let me know if you have any more thoughts (also, nitpick away - as someone learning Elixir, I'd like to make both the public API and internal code as intuitive / standard as possible).

**Comment by josevalim** [comment]
Looks great! The last final minor nits are:

1. In the `encode` function, I think you should expect it to always be a `Pgvector` and not call `Pgvector.new`. I believe most (if not all) Postgrex types avoid doing type casting on encoding time. This means your Ecto Type will change too: `load`/`dump` are no-ops (they receive and return Pgvectors) and cast can call `Pgvector.new` (i.e. we typically aim to know which data structures we are passing around and explicit conversions happens on `cast` and similar)

2. The binary pattern matching feature in Erlang/Elixir holds references to the original binary. So when you do `<<x, y, z::binary>>`, the `z::binary` is a reference to the binary. The benefit is less memory usage, the downside is that the larger binary will only be GCed when all of its parts are GCed. That's why on `init` we have this:

      def init(opts), do: Keyword.get(opts, :decode_binary, :copy)

So on decode - which receives the value from `init` as argument - you want to do this:

```elixir
  def decode(:copy) do
    quote do
      <<len::int32(), bin::binary-size(len)>> ->
        bin |> :binary.copy() |> Pgvector.new()
    end
  end

  def decode(_) do
    quote do
      <<len::int32(), bin::binary-size(len)>> ->
        bin |> Pgvector.new()
    end
  end
```

The default is `:copy` and I am not sure at the moment how good or bad that it is for vectors. I guess it depends on the size of vectors. If you want to allow that to be customized for pgvector exclusively, you can always add a new option on `init`:

      def init(opts), do: Keyword.get(opts, :decode_vectors, Keyword.get(opts, :decode_binary, :copy))

And that would allow folks to customize it when defining their own types module. Then I would wrap it up by adding `@moduledoc` and `@doc` to the public APIs and run `mix format`. :)

I will be super glad to answer any other questions.

**Comment by ankane** [comment]
Hey @josevalim, thanks again (and sorry for the delay)! Pushed another round of updates to the [struct3 branch](https://github.com/pgvector/pgvector-elixir/compare/struct3). It should have everything besides the docs and init option. Also, changed the field type from `Pgvector.Ecto.Vector` to `Pgvector` for simplicity. Let me know if you have any more thoughts (if you have the time) and will try to get this merged soon.

Also, fwiw, I'm not exactly sure how `cast` is used (none of the test cases seem affected by it).

**Comment by josevalim** [comment]
@ankane beautiful!

FWIW, I would keep the Ecto module as a separate one (Pgvector.Ecto.Vector was fine IMO) to keep the APIs separate, but I am glad to file it as "bikeshedding" if you prefer to go the route in your PR.

`dump` is used when going from `Schema -> DB`. `load` is `DB -> Schema`. `cast` is `External -> Schema`. If you do `from p in Post, where: p.vector == ^something`, `something` will be cast to the type of `p.vector`. For example, for an integer type, `load` and `dump` should be no-op (you get and return integers from the database), but you may want to try to cast a string received as an external parameter (from an HTTP form, for example) to an integer.

**Comment by ankane** [comment]
Thanks! It's now merged 🎉 🎉

Kept the Ecto module separate, and `cast` is now tested. Also, changed `Pgvector.new(binary)` to `Pgvector.from_binary(binary)` so `Pgvector.new` could be used for the string representation (`"[1,2,3]"`) in the future. Finally, I'm a bit hesitant to require `Pgvector.new` for encoding, so I've kept the current behavior for now.

I really, really appreciate all of the help!! (and am happy to continue discussing before the release if there's anything else)

**Comment by josevalim** [comment]
Thank _you_! I have checked it and it looks glorious! :shipit:

**Comment by ankane** [comment]
Awesome, 0.2.0 is out!

**Comment by ankane** [comment]
And thanks for the initial suggestion @seanmor5!

**Comment by honkfestival** [comment]
This is awesome, thanks @ankane and @josevalim!
